targets:
  $default:
    sources:
      - lib/**
      - lib/data/remote/graphql/commands/**
      - schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: lib/data/remote/graphql/commands/*.graphql
              output: lib//data/remote/graphql/graphql_api.dart
              naming_scheme: pathedWithFields
          scalar_mapping:
            - graphql_type: URI
              dart_type: String
            - graphql_type: DateTime
              dart_type: DateTime
            - graphql_type: HTML
              dart_type: String
