
name: CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter environment
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.2.1'
          channel: stable
      - run: flutter pub get
      - run: flutter test
